version: "3.8"
services:
  php:
    # build: .
    image: php
    ports:
      - "8080:80"
    expose:
      - 80
    container_name: meusite_php
    volumes:
      - .:/usr/share/nginx/html
  php-mysql:
    image: ${MYSQL_IMAGE}
    ports:
      - ${MYSQL_PORTS}
    container_name: ${MYSQL_NAME_CONTAINER}
    env_file:
      - mysql.env
