version: "3.8"
services:
  php:
    # build: .
    image: php_php
    ports:
      - "80:80"
      - 443:443
    expose:
      - 80
      - 443
    container_name: meusite_php
    restart: always
    volumes:
      - .:/usr/share/nginx/html
      - ./conf.d:/etc/nginx/conf.d
      - ./certbot:/etc/nginx/ssl
  php-mysql:
    image: ${MYSQL_IMAGE}
    ports:
      - ${MYSQL_PORTS}
    container_name: ${MYSQL_NAME_CONTAINER}
    env_file:
      - mysql.env
